### ISSUE TITLE
A Question Leaving SIP Disabled

### ISSUE THREAD

**Issue by tommyrot10** [VisualisationExpo/AquaLickX#3]
Dear developer,

This isn't an issue report, but there don't appear to be any FAQs nor a forum to contact you for questions, so I hope you don't mind my asking this here. Firstly, these UI enhancements look fantastic – just what I've been looking for. And owing to the way that recent versions of macOS are structured, this requires System Integrity Protection (SIP) to be enabled. Does SIP have to remain disabled? If you re-enable SIP, do all these enhancements disappear?
Thank you.

T

**Comment by Omoioma** [comment]
I am going to install the theme and re-enable SIP.
I will tell you how it goes.

**Comment by VisualisationExpo** [comment]
Re-enabling SIP will remove existing theming such as AquaLickX
