### ISSUE TITLE
Dangerous Syntax Error in Readme.md

### ISSUE THREAD

**Issue by buzz-lightsnack-2007** [VisualisationExpo/AquaLickX#4]
The theme works as expected in macOS Ventura, but for M1, it required deviating from the instructions in the ReadMe. The ReadMe has a syntax problem that, when left unchecked, will refer to a non-existent directory and therefore potentially brick a Mac after a reboot due to the changes not being blessed. 

The line in the ReadMe surrounding the problem is the following: 
> If you're on an Apple Silicon Mac then issue this bless command instead
> 
> ```sh
> sudo bless --mount "$HOME/mount/System/Library/CoreServices/" --setBoot --create-snapshot
> ```
> 
> Reboot your Mac using the regular reboot mechanisms immediately after issuing the bless command described above.

`mount` does not exist; I believe it supposedly refers to `livemount`. 

Nonetheless, thank you, and keep up the great work.

**Comment by VisualisationExpo** [comment]
Haven't had an issue with just using the --mount command here on Sonoma and M2 Mac mini..

I changed the Calendar icon a couple of days ago blessing the folder I changed the icon in.. 

**Edit: I see what you mean.. I'll change that to the right one**

Thank you..

_I guess I should go on an apology tour :)_
