### ISSUE TITLE
Color not filling up all of the menu bar on MacBook Pro

### ISSUE THREAD

**Issue by MWRevamped** [VisualisationExpo/AquaLickX#5]
No text needed, image is enough 
<img width="246" alt="Screenshot 2024-05-22 at 2 28 24 PM" src="https://github.com/VisualisationExpo/AquaLickX/assets/118232870/cbac7fa0-40b0-473d-ad45-225bb285af2c">

**Comment by VisualisationExpo** [comment]
Are you using this on newer macOS other than Monterey? That's a little detail that I'd like to learn if you can share.

**Comment by MWRevamped** [comment]
Yes

**Comment by VisualisationExpo** [comment]
Use different repo recently created

**Comment by MWRevamped** [comment]
Hello, sorry about continuing this but although the new repo does function, the bar is still not filled up fully, I probably should have included that I have a notched MacBook Pro.

**Comment by VisualisationExpo** [comment]
Thanks for re-opening the issue.

Strange.

I don't know how to emulate that menu bar type as I'm only using a Mac Mini M2 and prior to that, a 27" Intel iMac.

I have to use Kite Compositor to create the Core Animation Archives and you're the first person who've mention this.

Are the `.car` files different on your installation - I'll take a look and see if there's other `.car` files with a Menu bar Core Animation Archive to change.

I might not get to the bottom of it all, but I'll try my best to look through the other available `.car` files and the `.caar` files within.

**Comment by MWRevamped** [comment]
Ah, well I'd assume the .car files are the same, unless you mean the default system ones, the only thing that's really different is it seems that the menu bar is simply wider, here's the files just incase tho
[cars.zip](https://github.com/VisualisationExpo/AquaLickX/files/15473218/cars.zip)

**Comment by VisualisationExpo** [comment]
yes, I meant the default ones. I already have the themed ones as I made them.

Isn't the menu bar with the notch taller rather than wider?

Unfortunately, I don't think I can troubleshoot without access to a notch MacBook.

Also, I haven't really looked to see if there's more to be done. I have to be honest.

**Comment by MWRevamped** [comment]
yes, sorry, taller, I get those words mixed, and that's alright, thanks for taking my problem into account and have a good one!

**Comment by VisualisationExpo** [comment]
Can't fix. Not having a notch capable Mac.
