### ISSUE TITLE
Please update AquaLickX to Sonoma 14.7

### ISSUE THREAD

**Issue by nairda991** [VisualisationExpo/AquaLickX#6]
Hi,

Im big fan of this theme ,great work! It would be fantastic if you updated this to newest version of Sonoma, as there is lots of compatibility problems right now with 14.7 version.

It would be great if I could be using this theme in future too.

Greetings, Onni from Finland

**Comment by VisualisationExpo** [comment]
Thank you 🙂 

I'll install it on a Sonoma 14.7 installation and see what's up.

Could you write some of the issues just so I know a little of what to expect?

**Comment by VisualisationExpo** [comment]
Are you using this version:
https://github.com/VisualisationExpo/AquaLickX-Sonoma145Edition

Or the old AquaLickX version?

**Comment by nairda991** [comment]
hi, i dont exactly remember, but there was a lot of bugs, you sure notice them fast. also at some point it bricked my installation some way, like my finder wasnt working at alla or something… im sorry, i dont remember very well. But really big up if you do the update, i appreciate that even someone does work to bring that aqua theme for new macs!

Allan Nyholm Nielsen ***@***.***> kirjoitti 11.10.2024 kello 10.03:



Thank you 🙂

I'll install it on a Sonoma 14.7 installation and see what's up.

Could you write some of the issues just so I know a little of what to expect?

**Comment by nairda991** [comment]
I did use that version

Allan Nyholm Nielsen ***@***.***> kirjoitti 11.10.2024 kello 10.10:



Are you using this version or the older version?
https://github.com/VisualisationExpo/AquaLickX-Sonoma145Edition

**Comment by VisualisationExpo** [comment]
I'm a little challenged with my setup - I use Sonoma 14.7 in a virtual machine.. I have to figure out a good approach to getting it set up correctly

**Comment by VisualisationExpo** [comment]
I have a version ready for the light version Sonoma 14.7 that will need a little testing 

It works fine on my virtual machine with 14.7 installed. 

I'll share tonight. If someone will test

**Comment by VisualisationExpo** [comment]
[AquaLickX-147Sonoma.zip](https://github.com/user-attachments/files/17368232/AquaLickX-147Sonoma.zip)
@nairda991 please test this one

Only a light mode for now

**Comment by VisualisationExpo** [comment]
Updated here https://github.com/VisualisationExpo/AquaLickX-Sonoma145Edition
